CREATE TABLE COUNTRY (ID int PRIMARY KEY, NAME VARCHAR (100), CODE VARCHAR (10), REGEX VARCHAR (100));
CREATE TABLE CUSTOMER (ID int, NAME varchar (50), PHONE varchar (50), COUNTRY int NOT NULL );
Alter TABLE CUSTOMER ADD FOREIGN KEY (COUNTRY) references COUNTRY(ID);